spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&usePingMethod=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    设置文件上传默认大小
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

#配置mybatis的规则
mybatis:
  #  config-location: classpath:mybatis.xml  如果用configruation 就不要写这个，可以省去这个配置文件
  mapper-locations: classpath:mapper/*.xml
